config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # Maintenance Routes
  ################################
  # get 'maintenance', to: 'static_pages#about'
  # get '/' => redirect('/maintenance')
  # get '*path' => redirect('/maintenance')
  # put '/' => redirect('/maintenance')
  # put '*path' => redirect('/maintenance')
  # post '/' => redirect('/maintenance')
  # post '*path' => redirect('/maintenance')
  # delete '/' => redirect('/maintenance')
  # delete '*path' => redirect('/maintenance')
  ################################

  get 'public_data', to: 'public_data#show'

  resources :publishings, only: %i[new create destroy]
  post 'publishings/:id/approve', to: 'publishings#approve', as: 'publishings_approve'
  post 'publishings/:id/rescind_approval', to: 'publishings#rescind_approval', as: 'rescind_approval'

  resources :project_report_links, only: %i[index view] do
    get 'new_query_form'
    post 'options_form'
  end

  resources :searches, only: [:index]
  resources :funding_sources, only: [:index]
  resources :funding_sources_sd_meta_data, only: %i[create destroy]
  resources :sd_picods_types, only: [:index]
  resources :key_question_types, only: [:index]
  resources :sd_key_questions_key_question_types, only: %i[create destroy]
  resources :sd_key_questions_sd_picods, only: %i[create destroy]
  resources :sd_search_databases, only: %i[index create]
  resources :key_questions, only: [:index]
  resources :sd_key_questions, only: [:index] do
    get 'destroy_with_picodts', on: :member
  end
  resources :sd_meta_data_queries, only: %i[create update destroy]
  resources :review_types, only: %i[index create]
  resources :data_analysis_levels, only: [:index]

  devise_for :admins
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  devise_scope :user do
    post '/users/api_key_reset' => 'users/registrations#api_key_reset'
  end

  authenticate :admin do
    mount Searchjoy::Engine, at: 'searchjoy'
    mount Sidekiq::Web => '/sidekiq'
  end

  apipie
  namespace :api do
    namespace :v1 do
      resources :evidence_variables, only: %i[index show]

      resources :keywords, only: [:index]
      resources :users, only: [:index]
      resources :keywords, only: [:index]
      resources :timepoint_names, only: [:index]

      resources :citations, only: [:index] do
        collection do
          get 'titles'
          get 'project_citations_query'
        end
      end

      resources :projects, shallow: true do
        resources :citations, only: [:index] do
        end
        resources :extractions, only: [:index]
        resources :extraction_forms_projects do
          resources :extraction_forms_projects_sections, only: %i[index show] do
            post 'toggle_hiding', to: 'extraction_forms_projects_sections#toggle_hiding'
            resources :type1s, only: [:index]
          end
        end
      end
      resources :orderings do
        collection do
          patch 'update_positions'
        end
      end
    end # END namespace :v1 do

    namespace :v2 do
      resources :mesh_descriptors, only: [:index]
      resources :evidence_variables, only: %i[index show]
      get :public_projects, to: 'projects#public_projects'
      resources :projects, shallow: true do
        member do
          post :import_citations_fhir_json
        end
      end # END resources :projects, shallow: true do

      resources :extractions, only: [:show]
      resources :extraction_forms_projects_sections, only: [:show]
      resources :key_questions, only: [:show]
      resources :questions, only: [:show]
    end # END namespace :v2 do

    namespace :v3 do
      resources :projects, shallow: true, only: [:show] do
        resources :citations, only: %i[index show]
        resources :key_questions, only: %i[index show]
        resources :extractions, only: %i[index show]
        resources :sd_meta_data, only: %i[index show]
      end
      resources :extraction_forms_projects, shallow: true, only: [] do
        resources :extraction_forms_projects_sections, only: %i[index show]
      end
    end # END namespace :v3 do

    namespace :v4 do
      resources :projects, shallow: true, only: [:show] do
        resources :extractions, only: %i[index]
      end
    end # END namespace :v4 do
  end # END namespace :api do

  resources :comparisons
  resources :journals
  resources :keywords
  resources :records, only: [:update]
  resources :statusings, only: [:update]

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  resources :extractions_extraction_forms_projects_sections_type1s, only: [] do
    get 'get_results_populations', on: :member
  end

  resources :pictures, only: [:create] do
    delete :delete_image_attachment, on: :member
  end

  resources :sd_meta_data, shallow: true, only: [] do
    get 'preview'
    post 'section_update'
    post 'mapping_update'
    resources :sd_journal_article_urls, only: %i[create destroy update]
    resources :sd_other_items, only: %i[create destroy update]
    resources :sd_analytic_frameworks, only: %i[create destroy update]
    resources :sd_key_questions, only: %i[create destroy update]
    resources :sd_picods, only: %i[create destroy update]
    resources :sd_search_strategies, only: %i[create destroy update]
    resources :sd_grey_literature_searches, only: %i[create destroy update]
    resources :sd_prisma_flows, only: %i[create destroy update]
    resources :sd_summary_of_evidences, only: %i[create destroy update]
    resources :sd_result_items, only: %i[create destroy update]
  end

  resources :sd_meta_data_figures, only: %i[create destroy update]
  resources :sd_key_questions_projects, only: %i[create destroy]

  resources :sd_result_items, shallow: true, only: [] do
    resources :sd_narrative_results, only: %i[create destroy update]
    resources :sd_evidence_tables, only: %i[create destroy update]
    resources :sd_pairwise_meta_analytic_results, only: %i[create destroy update]
    resources :sd_network_meta_analysis_results, only: %i[create destroy update]
    resources :sd_meta_regression_analysis_results, only: %i[create destroy update]
  end

  resources :sd_narrative_results, shallow: true, only: [] do
    resources :sd_outcomes, only: %i[create destroy index]
  end
  resources :sd_evidence_tables, shallow: true, only: [] do
    resources :sd_outcomes, only: %i[create destroy index]
  end
  resources :sd_pairwise_meta_analytic_results, shallow: true, only: [] do
    resources :sd_outcomes, only: %i[create destroy index]
  end
  resources :sd_network_meta_analysis_results, shallow: true, only: [] do
    resources :sd_outcomes, only: %i[create destroy index]
  end
  resources :sd_meta_regression_analysis_results, shallow: true, only: [] do
    resources :sd_outcomes, only: %i[create destroy index]
  end

  get 'sd_key_questions/:id/fuzzy_match', to: 'sd_key_questions#fuzzy_match'

  resources :abstract_screenings, shallow: true, only: [] do
    resources :abstract_screenings_tags_users
    resources :abstract_screenings_reasons_users
  end

  resources :fulltext_screenings, shallow: true, only: [] do
    resources :fulltext_screenings_tags_users
    resources :fulltext_screenings_reasons_users
  end

  resources :abstract_screening_results, only: %i[show update destroy]
  resources :fulltext_screening_results, only: %i[show update]

  resources :result_statistic_sections_measures, only: %i[create]

  resources :data_audits, only: %i[index update]
  resources :projects, concerns: :paginatable, shallow: true do
    resources :consolidations

    get 'citation_lifecycle_management', to: 'abstract_screenings#citation_lifecycle_management'
    get 'kpis', to: 'abstract_screenings#kpis'
    post 'export_screening_data', to: 'abstract_screenings#export_screening_data'

    resources :abstract_screenings do
      get 'screen', to: 'abstract_screenings#screen'
      post 'update_word_weight', to: 'abstract_screenings#update_word_weight'
    end
    resources :fulltext_screenings do
      get 'screen', to: 'fulltext_screenings#screen'
    end

    resources :screening_forms

    resource :data_audit, only: [:create]
    resources :sd_meta_data

    member do
      get 'confirm_deletion'
      post 'import_csv'
      post 'import_ris'
      post 'import_endnote'
      post 'import_pubmed'
      post 'dedupe_citations'
      post 'create_citation_screening_extraction_form'
      post 'create_full_text_screening_extraction_form'
    end

    resources :citations do
    end

    resources :extractions do
      collection do
        get 'comparison_tool'
        get 'consolidate'
        get 'edit_type1_across_extractions'
      end

      member do
        get 'work'
        get 'reassign_extraction'
        put 'update_kqp_selections'
        get 'change_outcome_in_results_section', constraints: { format: 'js' }
      end

      resources :extractions_extraction_forms_projects_sections do
        resources :extractions_extraction_forms_projects_sections_question_row_column_fields, only: [:update]
        resources :extractions_extraction_forms_projects_sections_type1s, only: %i[edit update destroy] do
          member do
            get 'edit_timepoints'
            get 'edit_populations'
          end

          resources :extractions_extraction_forms_projects_sections_type1_rows, only: [:create] do
            resources :extractions_extraction_forms_projects_sections_type1_row_columns, only: [:create] do
              resources :result_statistic_sections, only: %i[edit update] do
                member do
                  post 'add_comparison'
                  delete 'remove_comparison'
                  get 'consolidate'
                  get 'manage_measures', constraints: { format: 'js' }
                end
              end
            end

app/controllers/api/v1/projects_controller.rb
module Api
  module V1
    class ProjectsController < BaseController
      before_action :set_project, only: %i[show update destroy]

      before_action :skip_authorization, only: %i[index show create]
      before_action :skip_policy_scope

      SORT = {  'updated-at': { updated_at: :desc },
                'created-at': { created_at: :desc } }.stringify_keys

      def_param_group :project do
        param :project, Hash, required: true, action_aware: true do
          param :name,              String, 'Name of the project'
          param :funding_source,    String, 'Who funds this project'
          param :prospero,          String, 'Prospero ID'
          param :doi,               String, 'Document Object Identifier'
          param :description,       String, 'Long description of project'
          param :attribution,       String, 'Project attribution'
          param :authors_of_report, String, 'Authors of Report'
          param :methodology,       String, 'Methodology description'
          param :notes,             String, 'Project notes'
        end
      end

      api :GET, '/v1/projects', 'List of projects'
      formats [:json]
      def index
        @projects = current_user.projects
                                .includes(:extraction_forms)
                                .includes(:key_questions)
                                .includes(publishing: [{ user: :profile }, approval: [{ user: :profile }]])
                                .by_query(@query).order(SORT[@order]).page(params[:page])
      end

      api :GET, '/v1/projects/:id', 'Show project by id'
      formats [:json]
      def show
        respond_with @project
      end

      api :POST, '/v1/projects', 'Create project'
      param_group :project
      formats ['json']
      def create
        @project = Project.new(project_params)
        flash[:notice] = 'Project was successfully created.' if @project.save
        respond_with @project
      end

      api :POST, '/v1/projects/:id', 'Update project'
      param_group :project
      formats ['json']
      def update
        authorize(@project)

        @project.update(project_params)
        flash[:notice] = 'Project was successfully updated.' if @project.save
        respond_with @project
      end

      private

      def set_project
        @project = Project.find(params[:id])
      end

      def project_params
        if action_name != 'create'
          params.require(:project).permit(policy(@project).permitted_attributes)
        else
          params.require(:project).permit(*ProjectPolicy::FULL_PARAMS)
        end
      end
    end
  end
end

app/controllers/api/v3/projects_controller.rb
class Api::V3::ProjectsController < Api::V3::BaseController
  before_action :set_project, only: [:show]

  def show
    authorize(@project)
    @project_bundle = AllResourceSupplyingService.new.find_by_project_id(@project.id)
    respond_to do |format|
      format.fhir_xml { render xml: @project_bundle }
      format.fhir_json { render json: @project_bundle }
      format.html { render json: @project_bundle }
      format.json { render json: @project_bundle }
      format.xml { render xml: @project_bundle }
      format.all { render text: 'Only HTML, JSON and XML are currently supported', status: 406 }
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def list_of_key_questions(extraction_forms_project)
    if extraction_forms_project.key_questions_projects.present?
      html = '<ul>'
      extraction_forms_project.key_questions_projects.each do |kqp|
        html += "<li>#{kqp.key_question.name}</li>"
      end
      html += '</ul>'

      raw(html)
    end
  end

  def empty_or_na(attribute)
    attribute.present? ? attribute : 'N/A'
  end

  def add_submenu?(controller_name, action_name, controller, publishable_record)
    (controller_name.eql?('projects') && !action_name.eql?('index') && !action_name.eql?('new')) ||
      (controller_name.eql?('sd_meta_data') && (action_name.eql?('index') || action_name.eql?('show') || action_name.eql?('edit'))) ||
      controller_name.eql?('abstract_screenings') ||
      controller_name.eql?('fulltext_screenings') ||
      controller_name.eql?('screening_forms') ||
      controller_name.eql?('extractions') ||
      controller_name.eql?('extraction_forms_projects') ||
      (controller_name.eql?('citations') && action_name.eql?('index')) ||
      (controller_name.eql?('questions') && (action_name.eql?('dependencies') ||
      action_name.eql?('edit'))) ||
      (controller_name.eql?('extractions_extraction_forms_projects_sections_type1s') && action_name.eql?('edit')) ||
      (controller_name.eql?('extraction_forms_projects_sections') && action_name.eql?('preview')) ||
      (controller_name.eql?('imports') && (action_name.eql?('new') || action_name.eql?('index'))) ||
      (controller.instance_of?(PublishingsController) && publishable_record.instance_of?(Project) && controller.action_name == 'new') ||
      controller_name.eql?('consolidations') ||
      (controller_name.eql?('imports') && action_name.eql?('show'))
  end

  def find_project(project, extraction, extraction_forms_project, question, extraction_forms_projects_section, publishable_record)
    project ||
      extraction.try(:project) ||
      extraction_forms_project.try(:project) ||
      question.try(:project) ||
      extraction_forms_projects_section.try(:project) ||
      publishable_record
  end
end

app/views/projects/edit/_added_citations_project_fields.html.slim
.nested-fields.added-item
  div[style='width: 92%;']
    .select-row[style='margin-top: 1rem; margin-bottom: 1rem;']
      = f.association :citation, as: :select, collection: [], prompt: 'Choose a citation', label: false, input_html: { class: 'citation-select' }
    .buttons-row.m-10
      .save-citation.button.success.small
        | Save Citation
      = link_to_remove_association 'Cancel', f, class: 'button alert small cancel-button'

app/views/projects/edit/_citation_screening_extraction_form.html.slim
- efp = @project.extraction_forms_projects.find_by(\
    extraction_forms_project_type: ExtractionFormsProjectType.find_by(name: "Citation Screening Extraction Form")\
  )

- if efp
  .grid-container
    .grid-x.grid-margin-x
      .cell.medium-3
        ul#citation-screening-extraction-tabs.vertical.tabs data-tabs=""
          li.tabs-title.is-active
            a href="#tabs-panel-acceptance-reasons" aria-selected="true" Acceptance Reasons
          li.tabs-title
            a href="#tabs-panel-deferment-reasons" Deferment Reasons
          li.tabs-title
            a href="#tabs-panel-rejection-reasons" Rejection Reasons

      .cell.medium-9
        .tabs-content data-tabs-content="citation-screening-extraction-tabs"
          - is_first = true
          - efp.extraction_forms_projects_sections.each do |efps|

            - if is_first
              .tabs-panel id="tabs-panel-#{ efps.section.name.parameterize }" class="is-active"
                .column.row
                  = render 'extraction_forms_projects/build/type2/type2_friendly_helper_message', efps: efps

                .column.row
                  = render 'extraction_forms_projects/build/type2/type2_link_to_type1', efps: efps

                .column.row
                  = render 'extraction_forms_projects/build/type2/type2_question_list', efps: efps

                - if efps.section.name == 'Risk of Bias Assessment'
                  .column.row
                    = render 'extraction_forms_projects/build/type2/type2_quality_predefined', efps: efps

                .button.create-button data-open="#{efps.id.to_s}-new-question-modal"
                  i.fi-plus>
                  | Add Question
                div.new-question-modal.reveal[data-reveal="" id="#{efps.id.to_s}-new-question-modal"]
                  = simple_form_for([efps, efps.questions.new], html: { data: { 'abide': '', 'live-validate': true } }) do |f|
                    = f.input :name, required: true, label: 'Question Text', autofocus: true
                    .form-actions
                      = button_tag type: 'submit', class: 'button create-button' do
                        i.fi-plus>
                        | Add Question

              - is_first = false

            - else
              .tabs-panel id="tabs-panel-#{ efps.section.name.parameterize }"
                .column.row
                  = render 'extraction_forms_projects/build/type2/type2_friendly_helper_message', efps: efps

                .column.row
                  = render 'extraction_forms_projects/build/type2/type2_link_to_type1', efps: efps

                .column.row
                  = render 'extraction_forms_projects/build/type2/type2_question_list', efps: efps

                - if efps.section.name == 'Risk of Bias Assessment'
                  .column.row
                    = render 'extraction_forms_projects/build/type2/type2_quality_predefined', efps: efps

                .button.create-button data-open="#{efps.id.to_s}-new-question-modal"
                  i.fi-plus>
                  | Add Question
                div.new-question-modal.reveal[data-reveal="" id="#{efps.id.to_s}-new-question-modal"]
                  = simple_form_for([efps, efps.questions.new], html: { data: { 'abide': '', 'live-validate': true } }) do |f|
                    = f.input :name, required: true, label: 'Question Text', autofocus: true
                    .form-actions
                      = button_tag type: 'submit', class: 'button create-button' do
                        i.fi-plus>
                        | Add Question

- else
  = link_to "Create Citation Screening Mini Extraction Form", create_citation_screening_extraction_form_project_path(@project), class: "button", method: :post

app/views/projects/edit/_keyword_fields.html.slim
.nested-fields.inner-inputs.kw-fields
  = f.input :name, placeholder: 'New Keyword', label: "Keyword Name"

  = link_to_remove_association '✖', f 

app/views/projects/edit/_manage_citations.html.slim
- if @project.has_duplicate_citations?
  div.row style="margin: 0;"
    div.columns.medium-12
      = link_to " (Dedupe citations in this project)", dedupe_citations_project_path(@project), method: :POST

div.row style="margin: 0;"
  div.columns.medium-9
    = simple_form_for @project do |form_project|
      #delete-citations-inner
        table#citations-table
          thead
            tr
              th Accession No. (e.g. PubMed ID)
              th RefID
              th Authors
              th Title
              th Edit
              th Delete?

          tbody
            - @citations.each do |citation|
              tr
                td style="text-align: center;" = citation.accession_number_alts
                td style="text-align: center;" = @citations_projects_dict[citation.id]&.refman
                td
                  div style="overflow: hidden; height: 18px;" title="#{citation.authors}" = citation.authors_short
                td
                  div style="overflow: hidden; height: 18px;" = citation.name
                td style="text-align: center;" = link_to 'Edit', edit_citation_path(citation, project_id: @project.id)
                = form_project.simple_fields_for :citations_projects, @citations_projects_dict[citation.id] do |sf_cp|
                  td style="text-align: center;" = sf_cp.check_box :_destroy, id: "sf_cp-#{citation.id}", style: "margin: 0"

      #delete-citations-submit-row.m-10
        .float-right
          input#delete-citations-select-all.m-10 type="checkbox"
          label.m-10 for='delete-citations-select-all' = 'Select All'
          = form_project.submit 'Delete Selected Citations', class: "button alert float-right"

  div.columns.medium-3
    div#top-anchor(data-sticky-container)
      div.sticky(data-sticky data-top-anchor="top-anchor" data-btm-anchor="btm-anchor" data-margin-top="5" data-check-every="0")

        - projects_user = ProjectsUser.find_by user: current_user, project: @project
        - unless projects_user.nil? && current_user.admin?
          - new_import = projects_user.imports.build

          /span data-tooltip="" data-click-open="true" title="You can import citations from .ris, .csv, PubMed ID list or EndNote Library"

          div style='display:flex; flex-direction:row;'
            span.import-headline
              h5 Upload Citation File(s)
            span.import-tooltip-icon style="margin-left: 3px;" data-open="import-tooltip-content"
              i.fi-info style="color:#28b0f3;font-size:20px;"
          .reveal#import-tooltip-content data-reveal="" style="font-size:large;line-height:25px;"
            | You can upload the following file formats to add citations to this project:
            ul style="padding-top:15px;font-size:large;line-height:25px;"
              li
                a href="https://srdrplus.s3.amazonaws.com/sample_ris.ris"
                  | RIS File (.ris)
              li
                a href="https://srdrplus.s3.amazonaws.com/sample_csv.csv"
                  | Comma Separated File (.csv)
              li
                a href="https://srdrplus.s3.amazonaws.com/sample_pubmed.txt"
                  | PubMed ID List (.txt)
              li
                a href="https://srdrplus.s3.amazonaws.com/sample_endnote.enw"
                  | EndNote File (.enw)

          #dropzone-div
            input#ris-file-type-id.hide value="#{ FileType.find_by(name: '.ris').id }"
            input#csv-file-type-id.hide value="#{ FileType.find_by(name: '.csv').id }"
            input#endnote-file-type-id.hide value="#{ FileType.find_by(name: '.enl').id }"
            input#pubmed-file-type-id.hide value="#{ FileType.find_by(name: 'PubMed').id }"
            input#json-file-type-id.hide value="#{ FileType.find_by(name: '.json').id }"
            = simple_form_for(new_import, remote: true, authenticity_token: true) do |f|
              .form-inputs
                = f.input :projects_user_id, as: :hidden, input_html: { value: projects_user.id }
                = f.input :import_type_id, as: :hidden, input_html: { value: ImportType.find_by(name: 'Citation').id }
                = simple_fields_for new_import.imported_files.build do |i_f|
                  #fileDropzone.dropzone name='mainFileUploader' dropzone-path="#{imports_path}"
                    .fallback
                      = i_f.input :file_type_id, as: :select, required: true, collection: FileType.all, selected: FileType.first.id
                      = i_f.input :content, as: :file, label: 'Citation File'
                      .form-actions
                        = f.button :submit, 'Upload file', class:"small", id:"submit-all"

div.row#btm-anchor style="margin: 10px 0 0 0;"
  div.columns.medium-12
    = simple_form_for( @project,
                       url: project_path(@project),
                       html: { id: 'citations-form' } ) do |f|
      = f.error_notification
      = f.hidden_field :redirect_path, value: project_citations_path(@project)

      div
        = link_to_add_association 'Add Citation', f, :citations_projects, partial: 'projects/edit/citations_project_fields'

app/views/projects/edit/_manage_extraction_forms.html.slim
- if @project.duplicate_extraction_form?

  p#warning.callout.alert
    ' Notice: Duplicate Extraction Form title detected. This is likely a mistake. Please correct below.

- if @project.key_questions_projects.blank?

  p#warning.callout.alert
    ' You must add Key Questions before creating Extraction Forms.

- else

  .table-scroll

    table.hover

      thead
        tr
          th = t('extraction_form_title')
          th = t('key_question_assignment')
          th = t('date_created')
          th = t('date_updated')

      tbody
        - @project.extraction_forms_projects.each do |efp|
          tr
            td = efp.extraction_form.name
            td = list_of_key_questions(efp)
            td = efp.created_at.in_time_zone(current_user.profile.time_zone).strftime('%b %-d, %Y - %l:%M %P')
            td = efp.updated_at.in_time_zone(current_user.profile.time_zone).strftime('%b %-d, %Y - %l:%M %P')
            td = link_to t('build'), build_extraction_forms_project_path(efp,
                   'panel-tab': efp.extraction_forms_projects_sections.present? ? efp.default_section_id : '')
            td = link_to t('rename'), edit_extraction_forms_project_path(efp)
            td = link_to t('remove'), efp, method: :delete, data: { confirm: t('confirm') }

  hr

  h6 = t('create_extraction_form')

  = simple_form_for(ExtractionFormsProject.new(project: @project), url: project_extraction_forms_projects_path(@project),
                                                                   html: { 'abide': '', 'live-validate': true }) do |f|
    == render 'extraction_forms_projects/form', f: f

app/views/projects/edit/_manage_information.html.slim
div class="mx-auto p-4 lg:p-8"
  /! Modal for project deletion.
  #modal-project-delete.reveal.large data-reveal=""

  h1 class="text-xl font-bold" Project Info

  = simple_form_for(@project, html: { id: "project-id-#{@project.id}", data: { 'abide': '', 'live-validate': true } }) do |f|
    = f.error_notification

    .alert.callout data-abide-error='' style='display: none;'
      p
        i.fi-alert>
        ' Please correct the errors below.

    .form-inputs
      = f.input :name, label: t('name'), required: true, hint: 'Name can\'t be blank'
      = f.input :description, label: t('topic_description'), input_html: { rows: 8 }
      = f.input :attribution, label: t('attribution'), input_html: { rows: 4 }
      = f.input :authors_of_report, label: t('authors_of_report'), input_html: { rows: 4 }
      - methodology_options = ["Systematic Review", "Technical Brief", "Rapid Review", "Evidence Map", ""]
      - if not methodology_options.include? f.object.methodology_description then methodology_options << f.object.methodology_description
      = f.input :methodology_description,
        as: :select,
        selected: f.object.methodology_description,
        collection: methodology_options,
        label: t('methodology_description'),
        input_html: { id: "project_method_description_select2", rows: 4 }
      = f.input :prospero, label: t('prospero_id')
      = f.input :doi, label: t('doi')
      = f.input :notes, label: t('notes'), input_html: { rows: 8 }
      = f.input :funding_source, label: t('funding_source')
      = f.association :mesh_descriptors,
        label: "Mesh Terms",
        input_html: { rows: 10 }
      .bg-blue-200.p-3.my-4.rounded
        = f.input :auto_train, label: 'Enable Auto Training', as: :boolean

    div class="mt-4 flex justify-between"
      div
        = f.button :submit, t('save_changes')
      div style="text-align: right;"
        = link_to "Delete Project", confirm_deletion_project_path(@project), method: :get, class: "alert button", remote: true

app/views/projects/edit/_manage_key_questions.html.slim
div class="mx-auto p-4 lg:p-8"
  - if @project.duplicate_key_question?

    p#warning.callout.alert
      ' Notice: Duplicate Key Question text detected. This is likely a mistake. Please correct below.
  h1 class="text-xl font-bold" Key Questions

  .table-scroll

    table.hover

      thead
        tr
          th style="min-width: 0; width: 10px;"
          th = t('key_question_text')
          th = t('assigned')
          th = t('date_created')
          th = t('date_updated')

      //orderable-table class is used for drag and drop
      tbody.orderable-list orderable-url="#{ update_positions_api_v1_orderings_url }"
        - @project.key_questions_projects.each do |kqp|
          tr.orderable-item [ table="key_questions_projects" position="#{ kqp.pos }" ordering-id="#{ kqp.id }" ]
            td.sort-handle style="min-width: 0; vertical-align: middle; width: 10px; cursor: pointer;"
              i class="fa fa-arrows"
            td = kqp.key_question.name
            td
              - if kqp.extraction_forms_projects_section.present?
                i.fi-check style='color: green;'
            td = kqp.created_at.in_time_zone(current_user.profile.time_zone).strftime('%b %-d, %Y - %l:%M %P')
            td = kqp.updated_at.in_time_zone(current_user.profile.time_zone).strftime('%b %-d, %Y - %l:%M %P')
            td = link_to edit_key_questions_project_path(kqp) do
              i.fi-pencil>
              = t('edit')
            td = link_to kqp, method: :delete, data: { confirm: t('confirm') } do
              i.fi-trash>
              = t('remove')

  hr

  h6 = t('create_key_question')

  = simple_form_for(KeyQuestionsProject.new(project: @project), url: project_key_questions_projects_path(@project),
                                                                html: { 'abide': '', 'live-validate': true },
                                                                remote: false) do |f|

    == render 'key_questions_projects/form', f: f

  - if @project.key_questions.present?
    - efp = @project.extraction_forms_projects.first
    = link_to 'Build Extraction Form', build_extraction_forms_project_path(efp.id, 'panel-tab': efp.default_section_id), class: 'button', style: 'float: right'
  - else
    div.button style='float: right; opacity: 0.25;' onclick="alert('You must add at least one key question first.')" Build Extraction Form

app/views/projects/edit/_tab_content.html.slim
.tabs-content data-tabs-content='project-tabs'

  #panel-project-information.tabs-panel.is-active
    == render 'projects/edit/manage_information'

  #panel-key-questions.tabs-panel style='margin-bottom: 3rem;'
    == render 'projects/edit/manage_key_questions'

  #panel-projects-users.tabs-panel
    == render 'projects/edit/manage_projects_users'